export enum ValidateProfileError {
    INCORRECT_USER_DATA = 'INCORRECT_USER_DATA',
    INCORRECT_SURNAME_DATA = 'INCORRECT_SURNAME_DATA',
    INCORRECT_EMAIL_DATA = 'INCORRECT_EMAIL_DATA',
    INCORRECT_PHONE_DATA = 'INCORRECT_PHONE_DATA',
    NO_DATA = 'NO_DATA',
    SERVER_ERROR = 'SERVER_ERROR'
}
